#!/bin/bash

#
# Notify PSU of constraint details
#


. ./op_functions

if [[ ! $1 ]]; then
  echo "Missing constraint file"
fi

curl -i -v -X POST -H "$(authHeader)" -H "$APP_JSON" --data "@$1" "$URL_BASE"/psu/v1/constraints
exitln $?
